Repository 100-hours-a-week/8-team-kar98-luckeat-fe, pull requests merged in 2025-03, with the labels that each got.

#38 26 refactoring s3 deployyml 수정/siena
  .github/workflows/s3-deploy.yml
  vite.config.js
Labels: 제안

#43 42 feat 클라우드프론트 개발운영환경 분리/siena
  .github/workflows/s3-deploy.yml
  vite.config.js
Labels: 제안

#45 페이지 복원
  src/pages/HomePage.jsx
  src/pages/MapPage.jsx
  src/pages/SignupPage.jsx
Labels: 버그-심각

#46 fix: Mixed Content error
  .github/workflows/s3-deploy.yml
  src/config/apiConfig.js
  vite.config.js
Labels: 제안

#52 fix: API 상대경로 사용
  src/api/apiClient.js
  src/config/apiConfig.js
  vite.config.js
Labels: 버그-일반

#63 58 google analytics, sentry 적용
  .github/workflows/s3-deploy.yml
  .gitignore
  index.html
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/HomePage.jsx
Labels: 제안

#97 fix: 개발/운영 환경에 따른 API URL 분리 설정
  src/api/apiClient.js
  src/config/apiConfig.js
  vite.config.js
Labels: 버그-일반

#107 fix: semantic-release 브랜치 설정 수정
  .releaserc.json
Labels: 제안

#111 메인 홈페이지 기능 및 UI 수정
  src/pages/HomePage.jsx
Labels: 제안

#114 fix: @semantic-release/git 플러그인 제거
  .releaserc.json
Labels: 제안

#118 홈페이지 스크롤 시 가게 목록 페이징 기능 추가 및 초기 표시 가게 목록 업데이트 로직 구현
  src/pages/HomePage.jsx
Labels: 제안

#122 chore: 환경별 API URL 분리 설정 추가
  .github/workflows/s3-deploy.yml
Labels: 제안

#143 가게 상세 페이지에서 공유 링크 생성 시 API URL 사용 및 인증 경로 수정
  src/App.jsx
  src/pages/StoreDetailPage.jsx
Labels: 버그-일반, 제안
