Repository 100-hours-a-week/8-team-kar98-luckeat-fe, pull requests merged in 2025-04, with the labels that each got.

#160 154 fe mappage category
  src/pages/MapPage.jsx
Labels: 제안

#179 177 fe 회원정보수정 페이지 스크롤 오류 수정
  src/pages/EditProfilePage.jsx
Labels: 버그-일반

#182 상품 상태 업데이트 및 삭제 기능 추가. 상품 관리 UI에서 유효기간 필드 제거 및 재고 수량 표시 방식 변경
  src/api/productApi.js
  src/api/storeApi.js
  src/components/products/ProductManagement.jsx
  src/pages/EditStorePage.jsx
Labels: 제안

#184 상품 및 가게 수정 페이지 유효성 검사 수정
  src/components/products/ProductManagement.jsx
  src/pages/EditStorePage.jsx
Labels: 버그-일반

#192 로그인 페이지 수정
  src/api/reservationApi.js
  src/pages/LoginPage.jsx
Labels: 버그-심각

#196 가게 업데이트 API에 카테고리 ID 추가
  src/api/storeApi.js
Labels: 버그-일반

#204 feat: 상품 예약 기능 개선 및 매진 상태 표시 추가
  src/pages/StoreDetailPage.jsx
Labels: 제안

#206 상품 관리 UI 개선 및 버튼 스타일 변경
  src/components/products/ProductManagement.jsx
Labels: 제안

#208 feat: 사용자 예약 정보 조회 로직 개선 및 환경 지표 계산 방식 변경
  src/api/reservationApi.js
  src/pages/LoginPage.jsx
  src/pages/MyPage.jsx
  src/pages/ReviewManagementPage.jsx
  src/pages/UserReservationsPage.jsx
Labels: 제안

#277 한국 시간대 설정 및 응답 데이터의 시간 필드 변환 기능 추가
  src/api/apiClient.js
Labels: 제안

#278 style: 토스트 메시지 z-index 수정 및 코드 포맷팅
  src/components/products/ProductManagement.jsx
  tailwind.config.js
Labels: 제안

#280 258 가게주소복사기능 UI개선
  src/pages/StoreDetailPage.jsx
Labels: 제안

#279 feat: 럭키트 설명 필드 유효성 검사 개선
  src/components/products/ProductManagement.jsx
Labels: 버그-일반

#285 사업자도 정보 수정 가능하도록 수정 및 UI개선
  src/components/products/ProductManagement.jsx
  src/pages/BusinessPage.jsx
  src/pages/StoreDetailPage.jsx
Labels: 제안

#296 url로 접근 시 유령 페이지가 보여지는 이슈 & 회원탈퇴시 오류 수정
  src/App.jsx
  src/context/AuthContext.jsx
  src/pages/EditProfilePage.jsx
  src/pages/NotFoundPage.jsx
  src/utils/apiMessages.js
Labels: 버그-일반

#311 재고 수량 유효성 검사 추가 (ProductManagement.jsx)
  src/components/products/ProductManagement.jsx
Labels: 제안

#351 가게상세페이지에서 리뷰 평점 표시 방식 개선 및 상품 정보 섹션 제거
  src/pages/StoreDetailPage.jsx
Labels: 제안

#356 닉네임 및 비밀번호 업데이트 로직 간소화, 성공 메시지 표시 방식 변경 및 비밀번호 입력 안내 문구 수정
  src/context/AuthContext.jsx
  src/pages/EditProfilePage.jsx
Labels: 버그-일반

#359 이미지 업로드 방식 개선 PR: Presigned URL 방식 도입
  .gitignore
  src/api/storeApi.js
  src/api/uploadApi.js
  src/pages/ReviewManagementPage.jsx
Labels: 제안

#363 fix: semantic-release 설정 수정 - beta 버전과 함께 patch/minor 버전도 올라가도록 변경
  .releaserc.json
Labels: 버그-일반

#365 fix: 예약 취소 후 토스트 메시지가 사라지지 않는 이슈 수정 및 표시 시간 2초로 변경
  src/pages/UserReservationsPage.jsx
Labels: 버그-일반

#367 style: 마이페이지 UI 개선
  src/pages/MyPage.jsx
Labels: 제안

#369 fix: 탭 클릭 시 스크롤 동작 수정 및 인디케이터 이슈 해결
  src/pages/StoreDetailPage.jsx
Labels: 버그-일반
